using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class CameraController : MonoBehaviour
{
    [Header ("Positions")]
    public Transform cameraPosition; // Variable que indica el valor Transform de la c치mara principal.      
    public Transform playerPosition; // Variable que indica el valor Transform del jugador.  

    private void LateUpdate()
    {
        // Actualizaci칩n que hace a la c치mara seguir la posici칩n del jugador.
        if (cameraPosition == null || playerPosition == null) 
        {   // no hacer nada, ya que no hay objeto que mover
            return; 
        }

        cameraPosition.transform.position = playerPosition.transform.position;
    }
}
